from discord import Message


class PlayItem:
    def __init__(
            self,
            message: Message,
            internal: bool,
            length: int,
            download_url: str,
            title: str = '',
            thumbnail: str = '',
            video_url: str = ''
    ):
        self.message: Message = message
        self.internal: bool = internal  # Used for signaling internal resources.
        self.length: int = length
        self.download_url: str = download_url  # URL generated by yt-dlp.
        self.title: str = title
        self.thumbnail: str = thumbnail  # URL for thumbnail.
        self.video_url: str = video_url  # Original URL for video.
